apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
  labels:
    app.kubernetes.io/instance: automation
    app.kubernetes.io/name: crossplane
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: crossplane-crds
            syncWave: "-1"
            repoURL: https://charts.crossplane.io/stable
            chart: crossplane
            targetRevision: "2.1.1"
            helmValues: |
              replicaCount: 1
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              rbacManager:
                enabled: false
            pruneBool: "false"
            selfHealBool: "false"
          - name: crossplane-main
            syncWave: "0"
            repoURL: https://charts.crossplane.io/stable
            chart: crossplane
            targetRevision: "2.1.1"
            helmValues: |
              replicaCount: 2
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 128Mi
              args:
                - --enable-usages
              rbacManager:
                replicaCount: 2
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 128Mi
            pruneBool: "true"
            selfHealBool: "true"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: automation
        app.kubernetes.io/name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: automation
      destination:
        namespace: crossplane-system
        server: https://kubernetes.default.svc
      source:
        repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          values: |
{{.helmValues}}
      syncPolicy:
        automated:
          prune: {{if eq .pruneBool "true"}}true{{else}}false{{end}}
          selfHeal: {{if eq .selfHealBool "true"}}true{{else}}false{{end}}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: ""
          kind: Secret
          namespace: crossplane-system
          jsonPointers:
            - /data
        - group: ""
          kind: ConfigMap
          namespace: crossplane-system
          jsonPointers:
            - /data
