apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/instance: network
    app.kubernetes.io/name: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argocd.localhost`)
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: http
          passHostHeader: true
      priority: 10

