apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-https
  namespace: authentik
  labels:
    app.kubernetes.io/instance: network
    app.kubernetes.io/name: authentik-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`authentik.localhost`)
      services:
        - name: authentik-server
          namespace: authentik
          port: 9443
          scheme: https
          passHostHeader: true
      priority: 10
  tls:
    certResolver: letsencrypt

