apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: platform-landing-https
  namespace: platform
  labels:
    app.kubernetes.io/instance: network
    app.kubernetes.io/name: platform-landing-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`localhost`) || Host(`platform.localhost`)
      services:
        - name: platform-landing
          namespace: platform
          port: 80
      priority: 5
  tls:
    certResolver: letsencrypt

