apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-https
  namespace: vault
  labels:
    app.kubernetes.io/instance: network
    app.kubernetes.io/name: vault-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`vault.localhost`)
      services:
        - name: vault
          namespace: vault
          port: 8200
          scheme: http
          passHostHeader: true
      priority: 10
  tls:
    secretName: vault-tls

