apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-configmaps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform
    app.kubernetes.io/name: platform-configmaps
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: HEAD
    path: argocd/app-of-apps/configmaps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

